---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: efs-addon-example
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi # Don't matter, it's elastic